// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:novaiptv/features/epg/data/models/epg_channel_model.dart';
import 'package:novaiptv/features/epg/data/models/epg_metadata_model.dart';
import 'package:novaiptv/features/epg/data/models/program_model.dart';
import 'package:novaiptv/features/playlist/data/models/channel_model.dart';
import 'package:novaiptv/features/playlist/data/models/playlist_model.dart';
import 'package:novaiptv/features/settings/data/models/app_settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsModelAdapter());
    registerAdapter(ChannelModelAdapter());
    registerAdapter(EpgChannelModelAdapter());
    registerAdapter(EpgMetadataModelAdapter());
    registerAdapter(PlaylistModelAdapter());
    registerAdapter(ProgramModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsModelAdapter());
    registerAdapter(ChannelModelAdapter());
    registerAdapter(EpgChannelModelAdapter());
    registerAdapter(EpgMetadataModelAdapter());
    registerAdapter(PlaylistModelAdapter());
    registerAdapter(ProgramModelAdapter());
  }
}
